#!/usr/bin/env bash

# fftitle: Give a video a nice, centered title.

set -eo pipefail

function help {
  echo "Usage: fftitle <input> <output> <title>"
  exit
}

function installed {
    cmd=$(command -v "${1}")

    [[ -n "${cmd}" ]] && [[ -f "${cmd}" ]]
    return ${?}
}

[[ $# -eq 3 && -f $1 && ! -f $2 && -n $3 ]] || help
installed ffmpeg || { >&2 echo "Missing ffmpeg."; exit 1; }

ffmpeg -i "${1}" -vf "drawtext=enable='between(t, 0, 10)':font=Sans:text='${3}':" \
    "fontcolor=white:fontsize=48:box=1:boxcolor=black@0.5:boxborderw=10:" \
    "x=(w-text_w)/2:y=(h-text_h)/2" -an "${2}"
