#!/usr/bin/env bash

# ffreverse: Reverse a video (and its audio).

set -eo pipefail

function help {
    echo "Usage: ffreverse <input> <output>"
    exit
}

function installed {
    cmd=$(command -v "${1}")

    [[ -n "${cmd}" ]] && [[ -f "${cmd}" ]]
    return ${?}
}

[[ $# -eq 2 && -f $1 && ! -f $2 ]] || help
installed ffmpeg || { >&2 echo "Missing ffmpeg."; exit 1; }

ffmpeg -i "${1}" -vf reverse -af areverse "${2}"
