#!/usr/bin/env bash

# ffmirror: (Horizontally) mirror a video.

set -eo pipefail

function help {
    echo "Usage: ffmirror <input> <output>"
    exit
}

function installed {
    cmd=$(command -v "${1}")

    [[ -n "${cmd}" ]] && [[ -f "${cmd}" ]]
    return ${?}
}

[[ $# -eq 2 && -f $1 && ! -f $2 ]] || help
installed ffmpeg || { >&2 echo "Missing ffmpeg."; exit 1; }

ffmpeg -i "${1}" -vf hflip "${2}"
