/*	bf.c
	Author: William Woodruff
	------------------------
	A short brainfuck 'compiler'.
	Generates C source code for a given brainfuck file,
	which can then be compiled to produce a functioning executable.
	Follows the original brainfuck implementation, which used a
	30,000 byte stack.

	This program is probably best wrapped in some short shell script
	that detects syntax errors in the generated C file, as they will
	invariably occur when equal pairs of '[' and ']' are not matched.
	However, I was too lazy to write one.
	------------------------
	This code is licensed by William Woodruff under the MIT License.
	http://opensource.org/licenses/MIT
*/

#include <stdio.h>
#include <stdlib.h>

int main(int argc, char const *argv[])
{
	if (argc != 3)
	{
		printf("Usage: %s <file.bf> <output file>\n", argv[0]);
		return EXIT_FAILURE;
	}
	else
	{
		FILE *bf_file = fopen(argv[1], "r");
		FILE *c_output = fopen(argv[2], "w");
		char c;

		fputs("/* generated by bf.c */#include <stdio.h>\nint main(void) {char s[30000]={0};char*sp=s;", c_output);

		while ((c = fgetc(bf_file)) != EOF)
		{
			switch(c)
			{
				case '>':
					fputs("++sp;", c_output);
					break;
				case '<':
					fputs("--sp;", c_output);
					break;
				case '+':
					fputs("++*sp;", c_output);
					break;
				case '-':
					fputs("--*sp;", c_output);
					break;
				case '.':
					fputs("putchar(*sp);", c_output);
					break;
				case ',':
					fputs("*sp=getchar();", c_output);
					break;
				case '[':
					fputs("while (*sp) {", c_output);
					break;
				case ']':
					fputs("}", c_output);
					break;
				default:
					break;
			}
		}

		fputs("}", c_output);
		fclose(bf_file);
		fclose(c_output);
		printf("Output written to: %s.\n", argv[2]);
	}
	return EXIT_SUCCESS;
}