/*	bf.c
	Author(s): William Woodruff, rmNULL
	------------------------
	A short brainfuck 'compiler'.
	Generates C source code for a given brainfuck file,
	which can then be compiled to produce a functioning executable.
	Follows the original brainfuck implementation, which used a
	30,000 byte stack.

	This program is probably best wrapped in some short shell script
	that detects syntax errors in the generated C file, as they will
	invariably occur when equal pairs of '[' and ']' are not matched.
	However, I was too lazy to write one.
	------------------------
	This code is licensed by William Woodruff under the MIT License.
	http://opensource.org/licenses/MIT
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main(int argc, char const *argv[])
{
	if (argc != 3)
	{
		printf("Usage: %s <file.bf> <output file>\n", argv[0]);
		return EXIT_FAILURE;
	}
	else
	{
		FILE *bf_file = fopen(argv[1], "r");
        	char op_buffer[30000] = { 0 };
        	int matches = 0;
		char c;

		while ((c = fgetc(bf_file)) != EOF)
		{
			switch(c)
			{
				case '>':
					strncat(op_buffer, "++sp;", 5);
					break;
				case '<':
					strncat(op_buffer, "--sp;", 5);
					break;
				case '+':
					strncat(op_buffer, "++*sp;", 6);
					break;
				case '-':
					strncat(op_buffer, "--*sp;", 6);
					break;
				case '.':
					strncat(op_buffer, "-putchar(*sp);", 14);
					break;
				case ',':
					strncat(op_buffer, "*sp=getchar();", 14);
					break;
				case '[':
					strncat(op_buffer, "while (*sp) {", 13);
					++matches;
					break;
				case ']':
					strncat(op_buffer, "}", 1);
					--matches;
					break;
				default:
					break;
			}
		}

        	/* It's a nasty move, please bear */
        	char *end = op_buffer + strlen(op_buffer);

        	if (matches)
        	    puts("note: unmatched brackets code will be purged by the compiler."
        	            "sorry, if that violates your freedom.");

        	while (matches)
            {
        	    if (matches < 0 && *--end == '}')
                {
        	            matches++;
        	    }
                else if (*--end == '{')
                {
        	            matches--;
        	            /* skip 'while (*sp) {' string; magicNumber 12 takes the
        	             * end pointer to 'w' of 'while' */
        	            end -= 12;
        	    }
        	}

        	*end++ = '}';
        	*end = '\0';

		FILE *c_output = fopen(argv[2], "w");
		fputs("/* generated by bf.c */#include <stdio.h>\nint main(void) {char s[30000]={0};char*sp=s;", c_output);
		fputs(op_buffer, c_output);
		fclose(c_output);
		fclose(bf_file);

		printf("Output written to: %s.\n", argv[2]);
	}
	return EXIT_SUCCESS;
}
