#!/usr/bin/env bash

#	mdmath.sh
#	Author: William Woodruff
#	------------------------
#	A basic preprocessor for LaTeX math equations in Markdown.
#	Converts LaTeX math formatting inside @@...@@ into images.
#	Images are generated by latex.codecogs.com.
#	Requires: curl, convert, sed, shasum.
#	------------------------
#	This code is licensed by William Woodruff under the MIT License.
#	http://opensource.org/licenses/MIT

function usage() {
	printf "Usage: $(basename ${0}) [-h] <file>\n"
	exit 1
}

function error() {
	>&2 printf "Fatal: ${@}. Exiting.\n"
	exit 2
}

function installed() {
	local cmd=$(command -v "${1}")

	[[ -n  "${cmd}" ]] && [[ -f "${cmd}" ]]
	return ${?}
}

installed curl || error "curl is required"
installed convert || error "convert is required"
installed sed || error "sed is required"
installed shasum || error "shasum is required"

[[ -z "${1}" ]] && usage
[[ -f "${1}" ]] || error "No such file: '${1}'"

# everything below this is ugly.

IFS=$'\n'
matches=($(sed -n 's,.*@@\(.*\)@@.*,\1,p' "${1}"))
unset IFS
slugs=( )

for i in "${!matches[@]}"; do
	sha=$(echo ${matches[i]} | shasum)
	slugs[${i}]="${sha:0:6}"
	curl -sG 'http://latex.codecogs.com/gif.latex' --data-urlencode "${matches[i]}" > "${slugs[i]}.gif"
	convert "${slugs[i]}.gif" "${slugs[i]}.png"

	matches[${i}]=$(printf '%s\n' "${matches[i]}" | sed -e 's/\\/\\\\/g' | sed -e 's/\^/\\\^/g')
	if [[ -z "${output}" ]]; then
		output=$(sed 's,@@'"${matches[i]}"'@@,![](./'"${slugs[i]}.png"'),' "${1}")
	else
		output=$(printf "${output}" | sed 's,@@'"${matches[i]}"'@@,![](./'"${slugs[i]}.png"'),')
	fi
done

echo "${output}"

